title:             Clean Blog
email:             nguyentruongky33@gmail.com
description:       My personal notes, codes, reviews, ideas
author:            Ky Nguyen
baseurl:           "/"
url:               "http://nguyentruongky.github.io"


# Social Profiles
# twitter_username:  SBootstrap
github_username:   nguyentruongky
# facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
