title:             < Code for life />
email:             nguyentruongky33@gmail.com
description:       My personal notes, codes, reviews, ideas
author:            Ky Nguyen
baseurl:           "/"
url:               "http://kynguyen.space"



# Social Profiles
skype_name: nguyentruongky3390
github_username:   nguyentruongky
mail: nguyentruongky33@gmail.com
linkedin_username: nguyentruongky3390

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
